### PR TITLE
Update to upstream 5.14

### PR DESCRIPTION
**Pull request by gsanchietti**
Try to avoid ftl loop block on bigger installations.

As per @cotosso request

NethServer/dev#6671

### CODE REVIEW

**Comment by gsanchietti** [comment]
RPM built manually:
[pihole-ftl-5.14-0.ns7.x86_64.rpm.gz](https://github.com/NethServer/pihole-ftl/files/8603517/pihole-ftl-5.14-0.ns7.x86_64.rpm.gz)

**Comment by gsanchietti** [comment]
@cotosso any news on this?

**Comment by cotosso** [comment]
@gsanchietti 
I installed it the first time the 3rd of May, but after a few hours I was forced to do a revert because of non clear problem of the network that I couldn't directly verify (I'm quite sure it wasn't because of this update but I couldn't do in other way).

Then I had the possibility to install for a 2nd time the update the 18th of May and it's behaving good so far.
Today I'm going to install it on 3 servers more in order to have a more reliable test base, in about a week I should be able to give my final confirmation.

**Comment by cotosso** [comment]
It seems to work well , but we need a week more to be fully sure, we will confirm definitively the 6/6

**Comment by cotosso** [comment]
After a long period of testing on multiple servers the update seems to have solved the previous problems and has not introduced any new ones so it can be released.

**Pull request merged**
